config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :baggages
  resources :reservations
  resources :flights
  resources :users

  resources :reservations do
    resources :baggages, only: :index
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
end

app/models/flight.rb
class Flight < ApplicationRecord
    has_many :reservations, dependent: :destroy

    enum flight_class: [ :'Jumbo', :'Private', :'Small' ]

    validates :manufacturer, presence: true
    validates :source, presence: true
    validates :destination, presence: true
    validates :source, comparison: { other_than: :destination }
    validates :cost, comparison: { greater_than: 0 }
    validates :cost_by_baggage_weight, comparison: { greater_than: 0 }
    validates :capacity, comparison: { greater_than: 0 }
    validates :passengers, comparison: { greater_than_or_equal_to: 0 }
    validates :passengers, comparison: { less_than_or_equal_to: :capacity }
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: %i[ show edit update destroy ]
  before_action :ensure_admin, only: %i[ edit create update destroy ]

  # GET /flights or /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1 or /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights or /flights.json
  def create
    @flight = Flight.new(flight_params)
    @flight.passengers = 0
        
    respond_to do |format|
      if @flight.save
        format.html { redirect_to flight_url(@flight), notice: "Flight was successfully created." }
        format.json { render :show, status: :created, location: @flight }
      else
        flash[:warning] = "Flight was not created."
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1 or /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to flight_url(@flight), notice: "Flight was successfully updated." }
        format.json { render :show, status: :ok, location: @flight }
      else
        flash[:warning] = "Flight was not updated."
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1 or /flights/1.json
  def destroy
    @flight.destroy

    respond_to do |format|
      format.html { redirect_to flights_url, notice: "Flight was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flight_params
      params.require(:flight).permit(:name, :flight_class, :manufacturer, :source, :destination, :capacity, :cost_by_baggage_weight, :cost)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_flight.html.erb
<div id="<%= dom_id flight %>">
  <p>
    <strong>Name:</strong>
    <%= flight.name %>
  </p>

  <p>
    <strong>Flight Class:</strong>
    <%= flight.flight_class %>
  </p>

  <p>
    <strong>Manufacturer:</strong>
    <%= flight.manufacturer %>
  </p>

  <p>
    <strong>Source:</strong>
    <%= flight.source %>
  </p>

  <p>
    <strong>Destination:</strong>
    <%= flight.destination %>
  </p>

  <p>
    <strong>Passengers:</strong>
    <%= flight.passengers %>
  </p>

  <p>
    <strong>Capacity:</strong>
    <%= flight.capacity %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= flight.passengers < flight.capacity ? "Available" : "Complete" %>
  </p>

  <p>
    <strong>Cost By Baggage Weight:</strong>
    <%= flight.cost_by_baggage_weight %>
  </p>
  
  <p>
    <strong>Cost:</strong>
    <%= flight.cost %>
  </p>
</div>

app/views/flights/_form.html.erb
<%= form_with(model: flight) do |form| %>
  <% if flight.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
        <% flight.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :flight_class, "Flight Class" %>
    <%= form.select :flight_class, options_for_select(Flight.flight_classes.map {|key, value| [key.titleize, Flight.flight_classes.key(value)]}, @flight.flight_class) %>
  </div>

  <div>
    <%= form.label :manufacturer, style: "display: block" %>
    <%= form.text_field :manufacturer %>
  </div>

  <div>
    <%= form.label :source, style: "display: block" %>
    <%= form.text_field :source %>
  </div>

  <div>
    <%= form.label :destination, style: "display: block" %>
    <%= form.text_field :destination %>
  </div>

  <div>
    <%= form.label :capacity, style: "display: block" %>
    <%= form.number_field :capacity, min: @flight.passengers.to_i %>
  </div>

  <div>
    <%= form.label :cost_by_baggage_weight, "Cost by Baggage Weight", style: "display: block" %>
    <%= form.number_field :cost_by_baggage_weight %>
  </div>

  <div>
    <%= form.label :cost, style: "display: block" %>
    <%= form.number_field :cost %>
  </div>

  <br>

  <div>
    <%= form.submit "Submit Flight" %> 
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<div style="color: red">
  <%= flash[:warning] %>
</div>

<br>

<%= render "form", flight: @flight %>

<br>

<div>
  <%= link_to "Show Flight", @flight %> 
  <br>
  <%= link_to "Back to Flights", flights_path %>
</div>

app/views/flights/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Flights</h1>

<table style="width:100%" >
  Search by source/destination <input id="search" oninput="search()">

  <thead>
      <tr>
        <th>Name&emsp;</th>
        <th>Flight Class&emsp;</th>
        <th>Manufacturer&emsp;</th>
        <th>Source&emsp;</th>
        <th>Destination&emsp;</th>
        <th>Passengers&emsp;</th>
        <th>Capacity&emsp;</th>
        <th>Status&emsp;</th>
        <th>Cost by Baggage Weight&emsp;</th>

        <th>Cost&emsp;</th>
        <th colspan="9"></th>
      </tr>
    </thead>
 
    <tbody id="flights">
    <% @flights.each do |flight| %>
      <tr>
        <td style="text-align:center"><%= flight.name %></td>
        <td style="text-align:center"><%= flight.flight_class %></td>
        <td style="text-align:center"><%= flight.manufacturer %></td>
        <td style="text-align:center"><%= flight.source %></td>
        <td style="text-align:center"><%= flight.destination %></td>
        <td style="text-align:center"><%= flight.passengers %></td>
        <td style="text-align:center"><%= flight.capacity %></td>
        <td style="text-align:center"><%= flight.passengers < flight.capacity ? "Available" : "Complete" %></td>
        <td style="text-align:center"><%= flight.cost_by_baggage_weight %></td>
        <td style="text-align:center"><%= flight.cost %></td>
        <td> <%= link_to "Show Flight", flight %> </td>
        <%if current_user.admin %>
          <td> <%= link_to "Edit Flight", edit_flight_path(flight) %> </td>
          <td> <%= button_to "Destroy Flight", flight_path(flight), method: :delete %> </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
<%if current_user.admin %>
  <%= link_to "New Flight", new_flight_path %>
<% end %>
</div>
<div>
  <%= link_to "Back to Home",  root_url %>
</div>

<script>

function search() {
  var filter = document.getElementById("search").value.trim().toLowerCase();
  var flights = document.getElementById("flights");
  for (var i = 0; i < flights.rows.length; i++) {
    var flight = flights.rows[i];
    var name = flight.cells[0].innerText.toLowerCase();
    var src = flight.cells[3].innerText.toLowerCase();
    var dest = flight.cells[4].innerText.toLowerCase();

    if (filter == "" || filter.includes(name) || filter.includes(src) || filter.includes(dest) || name.includes(filter) || src.includes(filter) || dest.includes(filter)) {
      flight.style.display = '';
    } else {
      flight.style.display = 'none';
    }
  }
}

</script>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<div style="color: red">
  <%= flash[:warning] %>
</div>

<br>

<%= render "form", flight: @flight %>

<br>

<div>
  <%= link_to "Back to Flights", flights_path %>
</div>

app/views/flights/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @flight %>

<div>
  <%= link_to "Edit Flight", edit_flight_path(@flight) %>
  <br>
  <%= link_to "Back to Flights", flights_path %>
  <br>
  <br>
  <%= button_to "Destroy Flight", @flight, method: :delete %>
</div>