config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :baggages
  resources :reservations
  resources :flights
  resources :users

  resources :reservations do
    resources :baggages, only: :index
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :reservations, dependent: :destroy
    validates :email, presence: true, uniqueness: true
    validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
    validates_format_of :credit_card, with: /(^$|(\A([0-9]{4})(-([0-9]{4})){3}))/
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    if current_user.admin
      @users = User.all
    else
      @users = [ current_user ]
    end
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: "User was successfully created." }
        format.json { render root_path, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update  
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    if @user.admin
      respond_to do |format|
        format.html { redirect_to users_url, notice: "Can't Destroy Admin" }
        format.json { head :no_content }
      end
    else
      @user.destroy

      respond_to do |format|
        format.html { redirect_to users_url, notice: "User was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      ensure_admin unless current_user.id == @user.id
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :mobile, :address, :credit_card)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.label :mobile, style: "display: block" %>
    <%= form.telephone_field :mobile %>
  </div>
  
  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_area :address %>
  </div>

  <div>
    <%= form.label :credit_card, style: "display: block" %>
    <%= form.text_field :credit_card, pattern: "\\A([0-9]{4})(-([0-9]{4})){3}", 
        title: "Use Format: 0123-4567-9810-1112" %>
  </div>

  <br>

  <div>
    <%= form.submit "Submit User" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= user.id %>
  </p>

  <p>
    <strong>Credit card:</strong>
    <%= user.credit_card %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= user.address %>
  </p>

  <p>
    <strong>Mobile:</strong>
    <%= user.mobile %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show User", @user %> 
  <br>
  <%= link_to "Back to Users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<table style="width:100%">
<% if @current_user.admin %>
  Search by user ID/name <input id="search" oninput="search()">
<% end %>

  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Mobile</th>
      <th>Address</th>
      <th>Credit Card</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody id="users">
    <% @users.each do |user| %>
      <tr>
        <td style="text-align:center"><%= user.id %></td>
        <td style="text-align:center"><%= user.name %></td>
        <td style="text-align:center"><%= user.email %></td>
        <td style="text-align:center"><%= user.mobile %></td>
        <td style="text-align:center"><%= user.address %></td>
        <td style="text-align:center"><%= user.credit_card %></td>
        <td><%= link_to 'Show User', user %></td>
        <td><%= link_to 'Edit User', edit_user_path(user) %></td>
        <%if !user.admin %>
          <td> <%= button_to 'Destroy User', user_path(user), method: :delete %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New User", new_user_path %>
<br>
<%= link_to "Back to Home", root_url %>

<script>

function search() {
  var filter = document.getElementById("search").value.trim().toLowerCase();
  var users = document.getElementById("users");
  for (var i = 0; i < users.rows.length; i++) {
    var user = users.rows[i];
    var id = user.cells[0].innerText.toLowerCase();
    var name = user.cells[1].innerText.toLowerCase();

    if (filter == "" || filter.includes(id) || filter.includes(name) || id.includes(filter) || name.includes(filter)) {
      user.style.display = '';
    } else {
      user.style.display = 'none';
    }
  }
}

</script>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to Home", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>