config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :baggages
  resources :reservations
  resources :flights
  resources :users

  resources :reservations do
    resources :baggages, only: :index
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
end

app/models/reservation.rb
class ReservationCreateValidator < ActiveModel::Validator
  def validate(reservation)
    return unless reservation.errors.blank?

    if reservation.flight.passengers + reservation.passengers > reservation.flight.capacity
        reservation.errors.add :base, "Too many passengers"
    end
  end
end

class ReservationUpdateValidator < ActiveModel::Validator
    def validate(reservation)
      return unless reservation.errors.blank?

      if reservation.flight.passengers + (reservation.passengers - reservation.old_passengers) > reservation.flight.capacity
        reservation.errors.add :base, "Too many passengers"
      end
    end
  end

class Reservation < ApplicationRecord
    attr_accessor :old_passengers

    belongs_to :user
    belongs_to :flight
    has_many :baggages, dependent: :destroy

    enum ticket_class: [ :'First', :'Business', :'Economy' ]
    enum amenities: [ :'None', :'Wifi', :'Meal Preference', :'Extra Legroom' ]

    validates :user, presence: true
    validates :flight, presence: true
    validates :passengers, presence: true
    validates :ticket_class, presence: true
    validates :amenities, presence: true

    validates :passengers, comparison: { greater_than: 0 }
    validates_with ReservationCreateValidator, on: :create
    validates_with ReservationUpdateValidator, on: :update

    trigger.after(:insert) do
        "UPDATE flights SET passengers = passengers + NEW.passengers WHERE id = NEW.flight_id;"
    end

    trigger.after(:update) do
        "UPDATE flights SET passengers = passengers + NEW.passengers - OLD.passengers WHERE id = NEW.flight_id;"
    end

    trigger.after(:delete) do
        "UPDATE flights SET passengers = passengers - OLD.passengers WHERE id = OLD.flight_id;"
    end

    def baggage_cost
        if self.baggages.empty?
            return 0
        end
        
        self.baggages.map { |x| x.cost }.inject(:+)
    end

    def cost
        self.passengers * self.flight.cost + baggage_cost
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]

  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all.select{|r| @current_user.admin || r.user_id == @current_user.id}
  end

  # GET /reservations/1 or /reservations/1.json
  def show
    @reservations = Reservation.find(params[:id])
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
    @reservation = Reservation.find(params[:id])
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(reservation_params.permit(:passengers, :ticket_class, :amenities))
    @reservation.flight = Flight.find_by_id(reservation_params[:flight_id])

    if current_user.admin
      @reservation.user = User.find_by_id(reservation_params[:user_id])
    else
      @reservation.user = current_user
    end
        
    respond_to do |format|
      if @reservation.save
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation }
      else
        flash[:warning] = "Reservation was not created."
        format.html { render :new, status: :unprocessable_entity}
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      @reservation.old_passengers = @reservation.passengers
      if @reservation.update(reservation_params)
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        @reservation.passengers = @reservation.old_passengers
        flash[:warning] = "Reservation was not updated."
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
      ensure_admin unless current_user.id == @reservation.user.id
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.fetch(:reservation, {})
      params.require(:reservation).permit(:flight_id, :user_id, :passengers, :ticket_class, :amenities)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :flight_id %>
    <%= form.select :flight_id, options_for_select(Flight.all.map {|f| [f.name, f.id]}, form.object.id), {}, onchange: "setMaxReservation()", disabled: form.object.persisted? %>
  </div>

  <% if @current_user.admin %>
    <div class="field">
      <%= form.label :user_id %>
      <%= form.select :user_id, options_for_select(User.all.map {|f| [f.name, f.id]}, form.object.id), disabled: form.object.persisted? %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :passengers %>
    <%= form.number_field :passengers, :id => 'passengers', min: 1, max: 0, onchange: "calculateTotalPrice()", oninput: "calculateTotalPrice()" %>
  </div>

  <div class="field">
    <label>Cost</label>
    <input id="cost" readonly="readonly" type="text">
  </div>

  <div class="field">
    <%= form.label :ticket_class, "Ticket Class" %>
    <%= form.select :ticket_class, options_for_select(Reservation.ticket_classes.map {|key, value| [key.titleize, Reservation.ticket_classes.key(value)]}, @reservation.ticket_class) %>
  </div>
 
  <div class="field">
    <%= form.label :amenities %>
    <%= form.select :amenities, options_for_select(Reservation.amenities.map {|key, value| [key.titleize, Reservation.amenities.key(value)]}, @reservation.amenities) %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit "Submit Reservation", id: "submit" %>
  </div>

<% end %>

<script type="text/javascript">
  var submit = document.getElementById("submit");
  var originalSubmitValue = submit.value;

  var costs = {
  <% Flight.all.each do |flight| %>
    '<%= flight.id %>': <%= flight.cost %>,
  <% end %>
  };

  var capacities = {
  <% Flight.all.each do |flight| %>
    '<%= flight.id %>': <%= flight.capacity %> - <%= flight.passengers %>,
  <% end %>
  };

  function getFlightId() {
    return document.getElementById('reservation_flight_id').value;
  }

  function calculateTotalPrice() {
    var price = costs[getFlightId()];
    document.getElementById('cost').value = document.getElementById('passengers').value * price;
  }

  function setMaxReservation() {
    var max = capacities[getFlightId()];

<% if !reservation.flight.nil? %>
    if (getFlightId() == <%= reservation.flight.id %>) {
      max += <%= reservation.passengers.to_i %>;
    }
<% end %>
    
    document.getElementById('passengers').max = max;

    var submit = document.getElementById("submit");
    if (max == 0) {
      submit.value = "Flight is full";
      submit.disabled = true;
    } else {
      submit.value = originalSubmitValue;
      submit.disabled = false;
    }
  }

  calculateTotalPrice();
  setMaxReservation();
</script>

app/views/reservations/_reservation.html.erb
<div id="<%= dom_id reservation %>">

<p>
  <strong>Confirmation Number:</strong>
  <%= @reservation.id %>
</p>

<p>
  <strong>Total Cost:</strong>
  <%= @reservation.cost %>
</p>

<p>
  <strong>Passengers:</strong>
  <%= @reservation.passengers %>
</p>

<p>
  <strong>Ticket Class:</strong>
  <%= @reservation.ticket_class %>
</p>

<p>
  <strong>Amenities:</strong>
  <%= @reservation.amenities %>
</p>

</div>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<div style="color: red">
  <%= flash[:warning] %>
</div>

<br>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Show Reservation", @reservation %>
  <br>
  <%= link_to "Back to Reservations", reservations_path %>
</div>

app/views/reservations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reservations</h1>

<table style="width:100%"> 
<% if @current_user.admin %>
  Search by user ID <input id="search" oninput="search()">
<% end %>

  <thead>
  <tr>
    <th>Confirmation Number&emsp;</th>
    <th>User ID&emsp;</th>
    <th>Flight Name&emsp;</th>
    <th>Total Cost&emsp;</th>
    <th>Passengers&emsp;</th>
    <th>Ticket Class&emsp;</th>
    <th>Amenities&emsp;</th>
    <th colspan="5"></th>
  </tr>
</thead>

  <tbody id="reservations">
    <% @reservations.each do |reservation| %>
      <tr>
        <td style="text-align:center"><%= reservation.id %></td>
        <td style="text-align:center"><%= reservation.user_id %></td>
        <td style="text-align:center"><%= reservation.flight.name %></td>
        <td style="text-align:center"><%= reservation.cost %></td>
        <td style="text-align:center"><%= reservation.passengers %></td>
        <td style="text-align:center"><%= reservation.ticket_class %></td>
        <td style="text-align:center"><%= reservation.amenities %></td>
        <td> <%= link_to "Show Reservation", reservation %> </td>
        <td> <%= link_to "Edit Reservation", edit_reservation_path(reservation) %> </td>
        <td> <%= link_to "See Baggages", reservation_baggages_path(reservation) %> </td>
        <td> <%= button_to 'Destroy Reservation', reservation_path(reservation), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= link_to "New Reservation", new_reservation_path %>
</div>
<div>
  <%= link_to "Back to Home",  root_url %>
</div>

<script>

function search() {
  var filter = document.getElementById("search").value.trim().toLowerCase();
  var reservations = document.getElementById("reservations");
  for (var i = 0; i < reservations.rows.length; i++) {
    var reservation = reservations.rows[i];
    var user_id = reservation.cells[1].innerText.toLowerCase();

    if (filter == "" || filter == user_id) {
      reservation.style.display = '';
    } else {
      reservation.style.display = 'none';
    }
  }
}

</script>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<div style="color: red">
  <%= flash[:warning] %>
</div>

<br>

<%= render "form", reservation: @reservation %>


<br>

<div>
  <%= link_to "Back to Reservations", reservations_path %>
</div>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @reservation %>

<div>
  <%= link_to "Edit Reservation", edit_reservation_path(@reservation) %> 
  <br>
  <%= link_to "Back to Reservations", reservations_path %>
  <br>
  <br>
  <%= button_to "Destroy Reservation", @flight, method: :delete %>
</div>