config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :baggages
  resources :reservations
  resources :flights
  resources :users

  resources :reservations do
    resources :baggages, only: :index
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
end

app/models/baggage.rb
class Baggage < ApplicationRecord
    belongs_to :reservation

    validates :weight, comparison: { greater_than: 0 }

    def cost
        self.weight * self.reservation.flight.cost_by_baggage_weight
    end
end

app/controllers/baggages_controller.rb
class BaggagesController < ApplicationController
  before_action :set_baggage, only: %i[ show edit update destroy ]

  # GET /baggages or /baggages.json
  def index
    @baggages = Baggage.all.select{|b| @current_user.admin || b.reservation.user_id == @current_user.id}
  end

  # GET /baggages/1 or /baggages/1.json
  def show
  end

  # GET /baggages/new
  def new
    @baggage = Baggage.new
  end

  # GET /baggages/1/edit
  def edit
  end

  # POST /baggages or /baggages.json
  def create
    reservation = Reservation.find_by_id(baggage_params[:bag_reservation_id])
    ensure_admin unless current_user.id  == reservation.user_id

    @baggage = Baggage.new(baggage_params.permit(:weight))
    @baggage.reservation = reservation

    respond_to do |format|
      if @baggage.save
        format.html { redirect_to baggage_url(@baggage), notice: "Baggage was successfully created." }
        format.json { render :show, status: :created, location: @baggage }
      else
        flash[:warning] = "Baggage was not created."
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @baggage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /baggages/1 or /baggages/1.json
  def update
    respond_to do |format|
      if @baggage.update(baggage_params.permit(:weight))
        format.html { redirect_to baggage_url(@baggage), notice: "Baggage was successfully updated." }
        format.json { render :show, status: :ok, location: @baggage }
      else
        flash[:warning] = "Baggage was not updated."
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @baggage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baggages/1 or /baggages/1.json
  def destroy
    @baggage.destroy

    respond_to do |format|
      format.html { redirect_to baggages_url, notice: "Baggage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baggage
      @baggage = Baggage.find(params[:id])
      ensure_admin unless current_user.id == @baggage.reservation.user.id
    end

    # Only allow a list of trusted parameters through.
    def baggage_params
      params.require(:baggage).permit(:bag_reservation_id, :weight)
    end
end

app/helpers/baggages_helper.rb
module BaggagesHelper
end

app/views/baggages/_baggage.html.erb
<div id="<%= dom_id baggage %>">
  <p>
    <strong>Reservation Confirmation Number:</strong>
    <%= baggage.reservation.id %>
  </p>

  <p>
    <strong>User ID:</strong>
    <%= baggage.reservation.user_id %>
  </p>
  
  <p>
    <strong>Flight Name:</strong>
    <%= baggage.reservation.flight.name %>
  </p>

  <p>
    <strong>Weight:</strong>
    <%= baggage.weight %>
  </p>

  <p>
    <strong>Cost:</strong>
    <%= baggage.cost %>
  </p>

</div>

app/views/baggages/_form.html.erb
<%= form_with(model: baggage) do |form| %>
  <% if baggage.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(baggage.errors.count, "error") %> prohibited this baggage from being saved:</h2>

      <ul>
        <% baggage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bag_reservation_id, "Reservation Confirmation Number" %>
    <%= form.select :bag_reservation_id, options_for_select(Reservation.all.select{|r| @current_user.admin || r.user_id == @current_user.id}.map {|r| [r.id.to_s, r.id]}), {}, disabled: form.object.persisted? %>
  </div>
  
  <div>
    <%= form.label :weight_in_pounds, "Baggage Weight (lbs)" %>
    <%= form.number_field :weight, min: 1, onchange: "calculateBagPrice()", oninput: "calculateBagPrice()" %>
  </div>

  <div>
    <label>Cost</label>
    <input id="cost" readonly="readonly" type="text">
  </div>

  <br>

  <div>
    <%= form.submit "Submit Baggage" %>
  </div>
<% end %>

<script type="text/javascript">
  var costs = {
  <% Flight.all.each do |flight| %>
    '<%= flight.id %>': <%= flight.cost_by_baggage_weight %>,
  <% end %>
  };

  function calculateBagPrice() {
    var price = costs[document.getElementById('baggage_bag_reservation_id').value];
    return document.getElementById('cost').value = document.getElementById('baggage_weight').value * price;
  }

  calculateBagPrice();
</script>

app/views/baggages/edit.html.erb
<h1>Editing Baggage</h1>

<div style="color: red">
  <%= flash[:warning] %>
</div>

<br>

<%= render "form", baggage: @baggage %>

<br>

<div>
  <%= link_to "Show Baggage", @baggage %> 
  <br>
  <%= link_to "Back to Baggages", baggages_path %>
</div>

app/views/baggages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Baggages</h1>

<table style="width:100%" >
  <thead>
      <tr>
        <th>Reservation Confirmation Number&emsp;</th>
        <th>User ID&emsp;</th>
        <th>Flight Number&emsp;</th>
        <th>Baggage Weight&emsp;</th>
        <th>Cost&emsp;</th>
        <th colspan="3"></th>
      </tr>
    </thead>

  <tbody>  
    <tbody>
    <% @baggages.each do |baggage| %>
      <tr>
        <td style="text-align:center"><%= baggage.reservation.id %></td>
        <td style="text-align:center"><%= baggage.reservation.user_id %></td>
        <td style="text-align:center"><%= baggage.reservation.flight.name %></td>
        <td style="text-align:center"><%= baggage.weight %></td>
        <td style="text-align:center"><%= baggage.cost %></td>
        <td> <%= link_to "Show Baggage", baggage %> </td>
        <td> <%= link_to "Edit Baggage", edit_baggage_path(baggage) %> </td>
        <td> <%= button_to "Destroy Baggage", baggage_path(baggage), method: :delete %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New Baggage", new_baggage_path %>
<br>
<%= link_to "Back to Home", root_url %>

app/views/baggages/new.html.erb
<h1>New Baggage</h1>

<div style="color: red">
  <%= flash[:warning] %>
</div>

<br>

<%= render "form", baggage: @baggage %>

<br>

<div>
  <%= link_to "Back to Baggages", baggages_path %>
</div>

app/views/baggages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @baggage %>

<div>
  <%= link_to "Edit Baggage", edit_baggage_path(@baggage) %>
  <br>
  <%= link_to "Back to Baggages", baggages_path %>
  <br>
  <br>
  <%= button_to "Destroy Baggage", @baggage, method: :delete %>
</div>